# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exportWindow(object):
    def setupUi(self, exportWindow):
        exportWindow.setObjectName("exportWindow")
        exportWindow.resize(400, 300)
        exportWindow.setStyleSheet("QDialog {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 24px;\n"
"    color: white;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 16px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    font-size: 16px;\n"
"    border: 2px solid white;\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    color: #007EA6;\n"
"}\n"
"\n"
"#line, #line_2 {\n"
"    color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(exportWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_main = QtWidgets.QHBoxLayout()
        self.hbox_main.setObjectName("hbox_main")
        self.vbox_apps_main = QtWidgets.QVBoxLayout()
        self.vbox_apps_main.setObjectName("vbox_apps_main")
        self.vbox_apps_all = QtWidgets.QVBoxLayout()
        self.vbox_apps_all.setObjectName("vbox_apps_all")
        self.lbl_apps = QtWidgets.QLabel(exportWindow)
        self.lbl_apps.setObjectName("lbl_apps")
        self.vbox_apps_all.addWidget(self.lbl_apps)
        self.chk_box_apps_all = QtWidgets.QCheckBox(exportWindow)
        self.chk_box_apps_all.setObjectName("chk_box_apps_all")
        self.vbox_apps_all.addWidget(self.chk_box_apps_all)
        self.line = QtWidgets.QFrame(exportWindow)
        self.line.setWindowModality(QtCore.Qt.WindowModal)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.vbox_apps_all.addWidget(self.line)
        self.vbox_apps_main.addLayout(self.vbox_apps_all)
        self.vbox_apps_container = QtWidgets.QVBoxLayout()
        self.vbox_apps_container.setObjectName("vbox_apps_container")
        self.vbox_apps_main.addLayout(self.vbox_apps_container)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vbox_apps_main.addItem(spacerItem)
        self.hbox_main.addLayout(self.vbox_apps_main)
        self.vbox_notes_main = QtWidgets.QVBoxLayout()
        self.vbox_notes_main.setObjectName("vbox_notes_main")
        self.vbox_main_inner = QtWidgets.QVBoxLayout()
        self.vbox_main_inner.setObjectName("vbox_main_inner")
        self.lbl_notes = QtWidgets.QLabel(exportWindow)
        self.lbl_notes.setObjectName("lbl_notes")
        self.vbox_main_inner.addWidget(self.lbl_notes)
        self.chk_box_notes_all = QtWidgets.QCheckBox(exportWindow)
        self.chk_box_notes_all.setObjectName("chk_box_notes_all")
        self.vbox_main_inner.addWidget(self.chk_box_notes_all)
        self.line_2 = QtWidgets.QFrame(exportWindow)
        self.line_2.setWindowModality(QtCore.Qt.WindowModal)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.vbox_main_inner.addWidget(self.line_2)
        self.vbox_notes_container = QtWidgets.QVBoxLayout()
        self.vbox_notes_container.setObjectName("vbox_notes_container")
        self.vbox_main_inner.addLayout(self.vbox_notes_container)
        self.vbox_notes_main.addLayout(self.vbox_main_inner)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vbox_notes_main.addItem(spacerItem1)
        self.hbox_main.addLayout(self.vbox_notes_main)
        self.verticalLayout.addLayout(self.hbox_main)
        self.hbox_btn_container = QtWidgets.QHBoxLayout()
        self.hbox_btn_container.setObjectName("hbox_btn_container")
        self.btn_exit = QtWidgets.QPushButton(exportWindow)
        self.btn_exit.setObjectName("btn_exit")
        self.hbox_btn_container.addWidget(self.btn_exit)
        self.btn_export = QtWidgets.QPushButton(exportWindow)
        self.btn_export.setObjectName("btn_export")
        self.hbox_btn_container.addWidget(self.btn_export)
        self.verticalLayout.addLayout(self.hbox_btn_container)

        self.retranslateUi(exportWindow)
        QtCore.QMetaObject.connectSlotsByName(exportWindow)

    def retranslateUi(self, exportWindow):
        _translate = QtCore.QCoreApplication.translate
        exportWindow.setWindowTitle(_translate("exportWindow", "Dialog"))
        self.lbl_apps.setText(_translate("exportWindow", "Apps"))
        self.chk_box_apps_all.setText(_translate("exportWindow", "All"))
        self.lbl_notes.setText(_translate("exportWindow", "Notes"))
        self.chk_box_notes_all.setText(_translate("exportWindow", "All"))
        self.btn_exit.setText(_translate("exportWindow", "Exit"))
        self.btn_export.setText(_translate("exportWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    exportWindow = QtWidgets.QDialog()
    ui = Ui_exportWindow()
    ui.setupUi(exportWindow)
    exportWindow.show()
    sys.exit(app.exec_())
