# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Runner2-Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Runner(object):
    def setupUi(self, Runner):
        Runner.setObjectName("Runner")
        Runner.resize(722, 510)
        Runner.setStyleSheet("#Runner {\n"
"    background-color: white;\n"
"}\n"
"")
        self.runner_main_layout = QtWidgets.QVBoxLayout(Runner)
        self.runner_main_layout.setContentsMargins(0, 0, 0, 0)
        self.runner_main_layout.setObjectName("runner_main_layout")
        self.tabWidget = QtWidgets.QTabWidget(Runner)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: white;\n"
"    font-size: 16px;\n"
"    height: 30px;\n"
"    width: 120px;\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #007EA6;\n"
"    color: white;\n"
"}\n"
"\n"
" QTabWidget::pane {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.apps_tab = QtWidgets.QWidget()
        self.apps_tab.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}\n"
"\n"
"#btn_run {\n"
"    background-color: white;\n"
"    color: #007EA6;\n"
"    border: 2px solid white;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"#btn_run:pressed {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #007EA6;\n"
"}\n"
"")
        self.apps_tab.setObjectName("apps_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.apps_tab)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbox_apps_btn_container = QtWidgets.QGridLayout()
        self.gbox_apps_btn_container.setContentsMargins(15, -1, 15, -1)
        self.gbox_apps_btn_container.setObjectName("gbox_apps_btn_container")
        self.main_add_category_btn = QtWidgets.QPushButton(self.apps_tab)
        self.main_add_category_btn.setStyleSheet("min-width: 150px;")
        self.main_add_category_btn.setObjectName("main_add_category_btn")
        self.gbox_apps_btn_container.addWidget(self.main_add_category_btn, 0, 1, 1, 1)
        self.apps_btn_delete = QtWidgets.QPushButton(self.apps_tab)
        self.apps_btn_delete.setStyleSheet("min-width: 150px;")
        self.apps_btn_delete.setObjectName("apps_btn_delete")
        self.gbox_apps_btn_container.addWidget(self.apps_btn_delete, 0, 3, 1, 1)
        self.apps_btn_edit = QtWidgets.QPushButton(self.apps_tab)
        self.apps_btn_edit.setStyleSheet("min-width: 150px;;")
        self.apps_btn_edit.setObjectName("apps_btn_edit")
        self.gbox_apps_btn_container.addWidget(self.apps_btn_edit, 0, 2, 1, 1)
        self.btn_run = QtWidgets.QPushButton(self.apps_tab)
        self.btn_run.setStyleSheet("min-width: 150px;")
        self.btn_run.setObjectName("btn_run")
        self.gbox_apps_btn_container.addWidget(self.btn_run, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gbox_apps_btn_container.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gbox_apps_btn_container.addItem(spacerItem1, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gbox_apps_btn_container)
        self.apps_container_vlayout = QtWidgets.QVBoxLayout()
        self.apps_container_vlayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.apps_container_vlayout.setObjectName("apps_container_vlayout")
        self.apps_scroll_area = QtWidgets.QScrollArea(self.apps_tab)
        self.apps_scroll_area.setStyleSheet("")
        self.apps_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.apps_scroll_area.setWidgetResizable(True)
        self.apps_scroll_area.setObjectName("apps_scroll_area")
        self.apps_scroll_area_widget = QtWidgets.QWidget()
        self.apps_scroll_area_widget.setGeometry(QtCore.QRect(0, 0, 720, 428))
        self.apps_scroll_area_widget.setObjectName("apps_scroll_area_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.apps_scroll_area_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.apps_scroll_area.setWidget(self.apps_scroll_area_widget)
        self.apps_container_vlayout.addWidget(self.apps_scroll_area)
        self.verticalLayout_2.addLayout(self.apps_container_vlayout)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/AppsIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.apps_tab, icon, "")
        self.notes_tab = QtWidgets.QWidget()
        self.notes_tab.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"")
        self.notes_tab.setObjectName("notes_tab")
        self.notes_tab_layout = QtWidgets.QVBoxLayout(self.notes_tab)
        self.notes_tab_layout.setContentsMargins(0, -1, 0, 0)
        self.notes_tab_layout.setObjectName("notes_tab_layout")
        self.add_note_layout = QtWidgets.QHBoxLayout()
        self.add_note_layout.setContentsMargins(15, -1, 15, -1)
        self.add_note_layout.setObjectName("add_note_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.add_note_layout.addItem(spacerItem2)
        self.main_add_notes_btn = QtWidgets.QPushButton(self.notes_tab)
        self.main_add_notes_btn.setStyleSheet("min-width: 150px;")
        self.main_add_notes_btn.setObjectName("main_add_notes_btn")
        self.add_note_layout.addWidget(self.main_add_notes_btn)
        self.btn_notes_edit = QtWidgets.QPushButton(self.notes_tab)
        self.btn_notes_edit.setStyleSheet("min-width: 150px;")
        self.btn_notes_edit.setObjectName("btn_notes_edit")
        self.add_note_layout.addWidget(self.btn_notes_edit)
        self.btn_notes_delete = QtWidgets.QPushButton(self.notes_tab)
        self.btn_notes_delete.setStyleSheet("min-width: 150px;")
        self.btn_notes_delete.setObjectName("btn_notes_delete")
        self.add_note_layout.addWidget(self.btn_notes_delete)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.add_note_layout.addItem(spacerItem3)
        self.notes_tab_layout.addLayout(self.add_note_layout)
        self.notes_scroll_outer_layout = QtWidgets.QVBoxLayout()
        self.notes_scroll_outer_layout.setObjectName("notes_scroll_outer_layout")
        self.notes_scroll_area = QtWidgets.QScrollArea(self.notes_tab)
        self.notes_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.notes_scroll_area.setWidgetResizable(True)
        self.notes_scroll_area.setObjectName("notes_scroll_area")
        self.notes_scroll_area_widget = QtWidgets.QWidget()
        self.notes_scroll_area_widget.setGeometry(QtCore.QRect(0, 0, 720, 428))
        self.notes_scroll_area_widget.setStyleSheet("QWidget {\n"
"    background-color: #007EA6;\n"
"}")
        self.notes_scroll_area_widget.setObjectName("notes_scroll_area_widget")
        self.notes_scroll_layout = QtWidgets.QVBoxLayout(self.notes_scroll_area_widget)
        self.notes_scroll_layout.setObjectName("notes_scroll_layout")
        self.notes_scroll_area.setWidget(self.notes_scroll_area_widget)
        self.notes_scroll_outer_layout.addWidget(self.notes_scroll_area)
        self.notes_tab_layout.addLayout(self.notes_scroll_outer_layout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/NotesIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.notes_tab, icon1, "")
        self.runner_main_layout.addWidget(self.tabWidget)

        self.retranslateUi(Runner)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Runner)

    def retranslateUi(self, Runner):
        _translate = QtCore.QCoreApplication.translate
        Runner.setWindowTitle(_translate("Runner", "WorkMate"))
        self.main_add_category_btn.setText(_translate("Runner", "Add Category"))
        self.apps_btn_delete.setText(_translate("Runner", "Delete Category"))
        self.apps_btn_edit.setText(_translate("Runner", "Edit Category"))
        self.btn_run.setText(_translate("Runner", "Run Active"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.apps_tab), _translate("Runner", "Apps"))
        self.main_add_notes_btn.setText(_translate("Runner", "Add Notes"))
        self.btn_notes_edit.setText(_translate("Runner", "Edit Notes"))
        self.btn_notes_delete.setText(_translate("Runner", "Delete Note"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notes_tab), _translate("Runner", "Notes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Runner = QtWidgets.QWidget()
    ui = Ui_Runner()
    ui.setupUi(Runner)
    Runner.show()
    sys.exit(app.exec_())
